spring:
  security:
    user:
      name: admin
      password: admin

    mvc:
      cors:
        allowed-origins: "http://localhost:8081"
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowed-headers: "*"
        allow-credentials: true
  user:
    name: admin
    password: admin
  jwt:
    secret: "tu_clave_secreta_muy_larga_y_segura_aqui"
    expiration: 3600000
  datasource:
    url: jdbc:mysql://localhost:3306/interb
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
